import { FrameStyle, GlazingOption, HardwareOption, StandardFrameSize } from "@/types"

export const STANDARD_FRAME_SIZES: StandardFrameSize[] = [
  {
    id: "size-4x6",
    name: "4 × 6",
    dimensions: "4 × 6 inch",
    widthInches: 4,
    heightInches: 6,
    recommendedUse: "Tabletop / Small",
  },
  {
    id: "size-6x8",
    name: "6 × 8",
    dimensions: "6 × 8 inch",
    widthInches: 6,
    heightInches: 8,
    recommendedUse: "Tabletop",
  },
  {
    id: "size-8x10",
    name: "8 × 10",
    dimensions: "8 × 10 inch",
    widthInches: 8,
    heightInches: 10,
    recommendedUse: "Small Wall",
  },
  {
    id: "size-10x12",
    name: "10 × 12",
    dimensions: "10 × 12 inch",
    widthInches: 10,
    heightInches: 12,
    recommendedUse: "Wall",
  },
  {
    id: "size-12x16",
    name: "12 × 16",
    dimensions: "12 × 16 inch",
    widthInches: 12,
    heightInches: 16,
    recommendedUse: "Wall",
  },
  {
    id: "size-12x18",
    name: "12 × 18",
    dimensions: "12 × 18 inch",
    widthInches: 12,
    heightInches: 18,
    recommendedUse: "Portrait / Wall",
  },
  {
    id: "size-16x20",
    name: "16 × 20",
    dimensions: "16 × 20 inch",
    widthInches: 16,
    heightInches: 20,
    recommendedUse: "Large Wall",
  },
  {
    id: "size-18x24",
    name: "18 × 24",
    dimensions: "18 × 24 inch",
    widthInches: 18,
    heightInches: 24,
    recommendedUse: "Large Wall",
  },
  {
    id: "size-20x30",
    name: "20 × 30",
    dimensions: "20 × 30 inch",
    widthInches: 20,
    heightInches: 30,
    recommendedUse: "Statement Frame",
  },
  {
    id: "size-24x36",
    name: "24 × 36",
    dimensions: "24 × 36 inch",
    widthInches: 24,
    heightInches: 36,
    recommendedUse: "Premium / Large Wall",
  },
]

export const FRAME_CATALOG: FrameStyle[] = [
  // ==========================================
  // 1. STANDARD FRAMES: Curated Premium Colors
  // ==========================================
  {
    id: "std-matte-black",
    name: "Gallery Matte Black",
    material: "modern",
    category: "standard",
    finish: "Satin Gallery Black",
    color: "#18181b",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Curator's Choice",
    description: "Clean, ultra-refined matte black gallery moulding with a subtle satin sheen.",
    borderCss: "1px solid rgba(255,255,255,0.08)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.7), inset 0 1px 1px rgba(255,255,255,0.12)",
    textureGradient: "linear-gradient(135deg, #27272a 0%, #18181b 50%, #09090b 100%)",
    accentHighlight: "rgba(255,255,255,0.15)",
  },
  {
    id: "std-studio-white",
    name: "Studio Archival White",
    material: "modern",
    category: "standard",
    finish: "Smooth Optic White",
    color: "#f4f4f5",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Archival",
    description: "Pure museum white moulding engineered to complement minimalist art and bright interiors.",
    borderCss: "1px solid rgba(0,0,0,0.08)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.35), inset 0 1px 2px rgba(255,255,255,0.9)",
    textureGradient: "linear-gradient(135deg, #ffffff 0%, #f4f4f5 55%, #e4e4e7 100%)",
    accentHighlight: "rgba(255,255,255,0.9)",
  },
  {
    id: "std-natural-oak",
    name: "Scandinavian Natural Oak",
    material: "wood",
    category: "standard",
    finish: "Nordic Blonde Hardwood",
    color: "#c89d6b",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Solid Oak",
    description: "Warm honey blonde Scandinavian oak with organic linear grain and soft matte seal.",
    borderCss: "1px solid rgba(255,255,255,0.15)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.5), inset 0 1px 2px rgba(255,255,255,0.25)",
    textureGradient: "linear-gradient(135deg, #d8af7e 0%, #c89d6b 45%, #a67c48 100%)",
    accentHighlight: "rgba(255,255,255,0.3)",
  },
  {
    id: "std-smoked-walnut",
    name: "Smoked American Walnut",
    material: "wood",
    category: "standard",
    finish: "Deep Roasted Espresso",
    color: "#422e23",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Artisan Wood",
    description: "Rich chocolate-toned walnut moulding with deep warmth and stately depth.",
    borderCss: "1px solid rgba(255,255,255,0.06)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.65), inset 0 1px 1px rgba(255,255,255,0.1)",
    textureGradient: "linear-gradient(135deg, #533b2e 0%, #422e23 50%, #291c15 100%)",
    accentHighlight: "rgba(255,255,255,0.12)",
  },
  {
    id: "std-brushed-brass",
    name: "Brushed Champagne Brass",
    material: "metal",
    category: "standard",
    finish: "Satin Architectural Metal",
    color: "#c5a059",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Brushed Metal",
    description: "Subtle champagne brass finish offering a warm metallic glow without reflective glare.",
    borderCss: "1px solid rgba(255,255,255,0.25)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.55), inset 0 1px 2px rgba(255,255,255,0.35)",
    textureGradient: "linear-gradient(135deg, #dfbc77 0%, #c5a059 45%, #9b7936 100%)",
    accentHighlight: "rgba(255,255,255,0.4)",
  },
  {
    id: "std-heritage-pine",
    name: "Heritage Forest Pine",
    material: "wood",
    category: "standard",
    finish: "Deep Moody Evergreen",
    color: "#1e382b",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Heritage",
    description: "Understated dark forest green moulding with vintage depth and character.",
    borderCss: "1px solid rgba(255,255,255,0.06)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.65), inset 0 1px 1px rgba(255,255,255,0.1)",
    textureGradient: "linear-gradient(135deg, #2b4f3d 0%, #1e382b 50%, #102118 100%)",
    accentHighlight: "rgba(255,255,255,0.12)",
  },
  {
    id: "std-terracotta",
    name: "Tuscan Terracotta",
    material: "modern",
    category: "standard",
    finish: "Fired Earth Mineral",
    color: "#9c4a38",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 12, right: 12, bottom: 12, left: 12 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    badge: "Warm Earth",
    description: "Rustic Tuscan red-clay tone crafted to infuse vibrant warmth into modern photography.",
    borderCss: "1px solid rgba(255,255,255,0.1)",
    boxShadowCss: "0 18px 36px -8px rgba(0,0,0,0.55), inset 0 1px 2px rgba(255,255,255,0.2)",
    textureGradient: "linear-gradient(135deg, #b85b46 0%, #9c4a38 50%, #6f3124 100%)",
    accentHighlight: "rgba(255,255,255,0.2)",
  },

  // ==========================================
  // 2. VINTAGE & ORNATE FRAMES (All Image Frames)
  // ==========================================
  {
    id: "vintage-gold-01",
    name: "Vintage Baroque Gold",
    material: "classic",
    category: "vintage-ornate",
    finish: "Gilded Ornate Baroque",
    color: "#a78657",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/gold-01.png",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 16, right: 16, bottom: 16, left: 16 },
    defaultWidth: 1.5,
    mouldingWidthRange: [0.75, 2.5],
    useNineSlice: true,
    sliceBorder: "16%",
    sliceRepeat: "round",
    badge: "Gilded Baroque",
    description: "Opulent gilded baroque moulding with handcrafted ornate corners.",
  },
  {
    id: "vintage-gold-02",
    name: "Vintage Antique Gold",
    material: "classic",
    category: "vintage-ornate",
    finish: "Burnished Antique Gold",
    color: "#9b7d51",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/gold-02.png",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 18, right: 18, bottom: 18, left: 18 },
    defaultWidth: 1.5,
    mouldingWidthRange: [0.75, 2.5],
    useNineSlice: true,
    sliceBorder: "18%",
    sliceRepeat: "round",
    badge: "Burnished Gold",
    description: "Classic burnished antique gold frame with sculpted ornate relief.",
  },
  {
    id: "vintage-cyan-01",
    name: "Vintage Cyan Patina",
    material: "classic",
    category: "vintage-ornate",
    finish: "Cyan Lacquered Patina",
    color: "#5e98a5",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/cyan-01.png",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 15, right: 15, bottom: 15, left: 15 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    useNineSlice: true,
    sliceBorder: "15%",
    sliceRepeat: "round",
    badge: "Vintage Patina",
    description: "Vintage lacquered cyan moulding with rich antiqued character.",
  },
  {
    id: "vintage-green-01",
    name: "Vintage Imperial Emerald",
    material: "classic",
    category: "vintage-ornate",
    finish: "Imperial Emerald & Gold",
    color: "#315540",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/green-01.png",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 18, right: 18, bottom: 18, left: 18 },
    defaultWidth: 1.5,
    mouldingWidthRange: [0.75, 2.5],
    useNineSlice: true,
    sliceBorder: "18%",
    sliceRepeat: "round",
    badge: "Imperial Emerald",
    description: "Deep emerald green vintage moulding with antiqued gold leaf edging.",
  },
  {
    id: "vintage-purple-01",
    name: "Vintage Royal Violet",
    material: "classic",
    category: "vintage-ornate",
    finish: "Deep Imperial Violet",
    color: "#754e83",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/purple-01.png",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 14, right: 14, bottom: 14, left: 14 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    useNineSlice: true,
    sliceBorder: "14%",
    sliceRepeat: "round",
    badge: "Imperial Velvet",
    description: "Ornate imperial violet studio moulding with subtle baroque accents.",
  },
  {
    id: "vintage-red-01",
    name: "Vintage Venetian Ruby",
    material: "classic",
    category: "vintage-ornate",
    finish: "Burnished Venetian Red",
    color: "#672b30",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/red-01.png",
    ratio: "1:1",
    aspectRatio: 1,
    rotation: 0,
    innerInset: { top: 14, right: 14, bottom: 14, left: 14 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    useNineSlice: true,
    sliceBorder: "14%",
    sliceRepeat: "round",
    badge: "Venetian Ruby",
    description: "Rich crimson burgundy ornate moulding with burnished vintage highlights.",
  },
]

export const GLAZING_OPTIONS: GlazingOption[] = [
  {
    id: "standard-acrylic",
    name: "Standard Framing Acrylic",
    description: "Lightweight, shatterproof 2.5mm acrylic with high clarity. Standard option.",
    priceMultiplier: 1.0,
    uvProtectionPercent: 66,
    reflectionGlareOpacity: 0.32,
  },
  {
    id: "non-glare",
    name: "Non-Glare Reflection Control",
    badge: "Popular",
    description: "Matte-etched acrylic that disperses specular highlights for zero room reflection.",
    priceMultiplier: 1.35,
    uvProtectionPercent: 78,
    reflectionGlareOpacity: 0.05,
  },
  {
    id: "museum-uv-99",
    name: "Museum Grade 99% UV Optium",
    badge: "Archival Preservation",
    description: "Anti-reflective optical coating blocking 99% of damaging UV light. True museum clarity.",
    priceMultiplier: 1.85,
    uvProtectionPercent: 99,
    reflectionGlareOpacity: 0.12,
  },
]

export const HARDWARE_OPTIONS: HardwareOption[] = [
  {
    id: "wire-hanger",
    name: "Coated Steel Braided Wire",
    description: "Pre-installed stainless steel wire with dual D-rings and wall hook included.",
    price: 0,
  },
  {
    id: "heavy-duty-cleat",
    name: "French Cleat Wall Mount",
    description: "Heavy-duty aluminum interlock bracket ensuring flush and level installation.",
    price: 18,
  },
  {
    id: "sawtooth",
    name: "Sawtooth Bracket Pair",
    description: "Compact dual sawtooth brackets for rapid flush mounting on drywall.",
    price: 0,
  },
]
