import { FrameStyle, GlazingOption, HardwareOption } from "@/types"

export const FRAME_CATALOG: FrameStyle[] = [
  {
    id: "cyan-1-1",
    name: "Cyan (1:1)",
    material: "modern",
    finish: "Cyan Lacquered",
    color: "#06b6d4",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/cyan-1-1.png",
    ratio: "1:1",
    aspectRatio: 1,
    innerInset: { top: 14, right: 13.5, bottom: 13.5, left: 14 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    description: "Contemporary cyan moulding formatted for square prints and photography.",
  },
  {
    id: "cyan-16-9",
    name: "Cyan (16:9)",
    material: "modern",
    finish: "Cyan Lacquered",
    color: "#06b6d4",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/cyan-16-9.png",
    ratio: "16:9",
    aspectRatio: 16 / 9,
    innerInset: { top: 17.6, right: 10.4, bottom: 16.7, left: 11.7 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    description: "Widescreen horizontal profile in bold modern cyan.",
  },
  {
    id: "cyan-3-4",
    name: "Cyan (3:4)",
    material: "modern",
    finish: "Cyan Lacquered",
    color: "#06b6d4",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/cyan-3-4.png",
    ratio: "3:4",
    aspectRatio: 3 / 4,
    innerInset: { top: 13.6, right: 17.4, bottom: 11.4, left: 17.4 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    description: "Vertical portrait gallery profile in vibrant cyan finish.",
  },
  {
    id: "gold-1-1",
    name: "Gold (1:1)",
    material: "classic",
    finish: "Burnished Gold",
    color: "#eab308",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/gold-1-1.png",
    ratio: "1:1",
    aspectRatio: 1,
    innerInset: { top: 15.5, right: 15.7, bottom: 14.7, left: 15 },
    defaultWidth: 1.5,
    mouldingWidthRange: [0.75, 2.5],
    description: "Opulent gilded gold moulding cut for square art compositions.",
  },
  {
    id: "gold-16-9",
    name: "Gold (16:9)",
    material: "classic",
    finish: "Burnished Gold",
    color: "#eab308",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/gold-16-9.png",
    ratio: "16:9",
    aspectRatio: 16 / 9,
    innerInset: { top: 17.3, right: 12.7, bottom: 17.3, left: 11.4 },
    defaultWidth: 1.5,
    mouldingWidthRange: [0.75, 2.5],
    description: "Landscape cinematic profile with luxurious gilded gold borders.",
  },
  {
    id: "gold-3-4",
    name: "Gold (3:4)",
    material: "classic",
    finish: "Burnished Gold",
    color: "#eab308",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/gold-3-4.png",
    ratio: "3:4",
    aspectRatio: 3 / 4,
    innerInset: { top: 13.1, right: 17.1, bottom: 12.4, left: 16.2 },
    defaultWidth: 1.5,
    mouldingWidthRange: [0.75, 2.5],
    description: "Classic vertical portrait frame layered in warm gilded gold.",
  },
  {
    id: "purple-1-1",
    name: "Purple (1:1)",
    material: "modern",
    finish: "Deep Royal Violet",
    color: "#a855f7",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/purple-1-1.png",
    ratio: "1:1",
    aspectRatio: 1,
    innerInset: { top: 13.3, right: 24.8, bottom: 12.5, left: 13.2 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    description: "Sleek royal purple studio moulding for modern square canvases.",
  },
  {
    id: "purple-16-9",
    name: "Purple (16:9)",
    material: "modern",
    finish: "Deep Royal Violet",
    color: "#a855f7",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/purple-16-9.png",
    ratio: "16:9",
    aspectRatio: 16 / 9,
    innerInset: { top: 16.8, right: 15.4, bottom: 15.8, left: 11.4 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    description: "Panoramic horizontal frame washed in velvet violet tones.",
  },
  {
    id: "purple-3-4",
    name: "Purple (3:4)",
    material: "modern",
    finish: "Deep Royal Violet",
    color: "#a855f7",
    price: 240,
    pricePerFoot: 240,
    imageUrl: "/images/frame/purple-3-4.png",
    ratio: "3:4",
    aspectRatio: 3 / 4,
    innerInset: { top: 11.9, right: 15.6, bottom: 11.9, left: 15.6 },
    defaultWidth: 1.25,
    mouldingWidthRange: [0.75, 2.5],
    description: "Atmospheric portrait frame finished in deep regal purple.",
  },
]

export const GLAZING_OPTIONS: GlazingOption[] = [
  {
    id: "standard-acrylic",
    name: "Standard Framing Acrylic",
    description: "Lightweight, shatterproof 2.5mm acrylic with high clarity. Standard option.",
    priceMultiplier: 1.0,
    uvProtectionPercent: 66,
    reflectionGlareOpacity: 0.32,
  },
  {
    id: "non-glare",
    name: "Non-Glare Reflection Control",
    badge: "Popular",
    description: "Matte-etched acrylic that disperses specular highlights for zero room reflection.",
    priceMultiplier: 1.35,
    uvProtectionPercent: 78,
    reflectionGlareOpacity: 0.05,
  },
  {
    id: "museum-uv-99",
    name: "Museum Grade 99% UV Optium",
    badge: "Archival Preservation",
    description: "Anti-reflective optical coating blocking 99% of damaging UV light. True museum clarity.",
    priceMultiplier: 1.85,
    uvProtectionPercent: 99,
    reflectionGlareOpacity: 0.12,
  },
]

export const HARDWARE_OPTIONS: HardwareOption[] = [
  {
    id: "wire-hanger",
    name: "Coated Steel Braided Wire",
    description: "Pre-installed stainless steel wire with dual D-rings and wall hook included.",
    price: 0,
  },
  {
    id: "heavy-duty-cleat",
    name: "French Cleat Wall Mount",
    description: "Heavy-duty aluminum interlock bracket ensuring flush and level installation.",
    price: 18,
  },
  {
    id: "sawtooth",
    name: "Sawtooth Bracket Pair",
    description: "Compact dual sawtooth brackets for rapid flush mounting on drywall.",
    price: 0,
  },
]
